### ISSUE TITLE
Errors with generate

### ISSUE THREAD

**Issue by forrestblade** [abhijithvijayan/portfolio-cli#10]
```

C:\Users\forre\Documents>npx @abhijithvijayan/portfolio generate portfolio
npx: installed 160 in 22.46s

Error: Command failed with exit code 128: git commit -m "⚡️ Initial commit from @abhijithvijayan/portfolio CLI"
    at makeError (C:\Users\forre\AppData\Roaming\npm-cache\_npx\16188\node_modules\@abhijithvijayan\portfolio\node_modules\execa\lib\error.js:56:11)
    at Function.module.exports.sync (C:\Users\forre\AppData\Roaming\npm-cache\_npx\16188\node_modules\@abhijithvijayan\portfolio\node_modules\execa\index.js:188:17)
    at performInitialCommit (C:\Users\forre\AppData\Roaming\npm-cache\_npx\16188\node_modules\@abhijithvijayan\portfolio\source\generate.js:49:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async generatePortfolio (C:\Users\forre\AppData\Roaming\npm-cache\_npx\16188\node_modules\@abhijithvijayan\portfolio\source\generate.js:88:2)
    at async C:\Users\forre\AppData\Roaming\npm-cache\_npx\16188\node_modules\@abhijithvijayan\portfolio\source\index.js:61:3
```

**Comment by abhijithvijayan** [comment]
Is this still happening? 

The error occured on committing the initial git tracking.

Have you configured git correctly?

Test if 
`git config --global user.name`
and
`git config --global user.email`
returns your git info.

**Comment by abhijithvijayan** [comment]
Please configure git to use yout GitHub username and commit email id(available from Settings->Emails)

```
git config --global user.name "yourusername"

git config --global user.email "githubcommitemail"
```
